### ISSUE TITLE
Mapbox GL optimization

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#71] opened 2015-11-09 16:35 UTC
What parts of V6 implement to make the `open-streets.tm2source` version better usable with MapBox GL JS styles?

**Comment by klokan** [comment] 2015-11-11 14:10
The latest https://github.com/mapbox/mapbox-studio-osm-bright.tm2 and a few others .tm2 on MapBox GitHub are already powered by V6.
We could indeed visually try these - and of course test against the MapBox GL JSON styles available in https://github.com/mapbox/mapbox-gl-styles and latest MapBox Studio.

**Comment by manuelroth** [comment] 2015-11-16 15:27
- I added generalization to the water layer (03d0da2) to solve the problem @klokan described in the last pull request. 
- Now we show the country labels with scalerank 1 starting zoomlevel 1 like streets v6 does (80f4692). 
- I couldn't find a solution for the overlapping place label problem, I tried to move the place_label layer up in the source project and increase the buffer size, but both approaches didn't worked.
- I opened an issue in the mapbox gl js repository (https://github.com/mapbox/mapbox-gl-js/issues/1729), maybe they know what the problem could be.

![bildschirmfoto 2015-11-16 um 16 09 34](https://cloud.githubusercontent.com/assets/1810384/11185738/833f8412-8c7e-11e5-9314-98189a6fc81f.png)

**Comment by manuelroth** [comment] 2015-11-16 17:39
Apparently the overlapping problem is a known issue of mapbox gl. They closed my issue because it is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/757. A fix is in the works.

**Comment by lukasmartinelli** [comment] 2015-11-16 17:44
Apart from that we put quite some time in it last week to make sure everything looks good on v6...so from my standpoint of view the big nasty things are done in the Mapbox GL optimization task.

**Comment by klokan** [comment] 2015-11-18 16:00
Latest Switzerland z14: http://osm.tileserver.com/open-streets/bright-v8ch.html#8/46.800/8.800
Latest World z7 to http://osm.tileserver.com/open-streets/bright-v8world.html#3.92/41.73/1.87

Both looks quite OK.

Have you checked the size of biggest tiles on the latest version?

**Comment by manuelroth** [comment] 2015-11-20 08:38
I want to clarify the confusion around the OSM Bright style for Mapbox GL and the normal TM2-Style.
![bildschirmfoto 2015-11-20 um 09 22 02](https://cloud.githubusercontent.com/assets/1810384/11295028/7256588c-8f68-11e5-9afa-315837953f79.png)

On the left side is the Mapbox GL version with this style https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/bright-v8.json

On the right side is the normal raster tile version with this style https://github.com/mapbox/mapbox-studio-osm-bright.tm2.git

There is somehow a difference between the Mapbox GL OSM Bright and the TM2 OSM Bright style.

**Comment by klokan** [comment] 2015-11-30 15:37
Compare our tiles (and their size) to V6 - to be done in #77

**Comment by klokan** [comment] 2015-11-30 15:41
If we find a serious problem let's reopen or create a new ticket.

**Closed by klokan** 2015-11-30 15:41 UTC
Labels: evaluation
