### ISSUE TITLE
Missing buildings

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#278] opened 2016-04-24 18:49 UTC
Missing in the mapping?

<img width="816" alt="compare_open_streets_with_mapbox_streets" src="https://cloud.githubusercontent.com/assets/1288339/14769650/c69005a4-0a5d-11e6-8fc4-f1243e780c2e.png">

<img width="932" alt="compare_open_streets_with_mapbox_streets" src="https://cloud.githubusercontent.com/assets/1288339/14769659/e7d83c4a-0a5d-11e6-9270-eab359354964.png">

**Comment by manuelroth** [comment] 2016-04-25 09:50
@lukasmartinelli Could not reproduce it on the master branch, maybe has something to do with collecting of buildings on cluster_road branch?- Think we can close this for now, as we anyways do not plan to collect buildings to one geometry.
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14780097/8e1fefd0-0adb-11e6-8ebc-247e90cd6088.png)

**Closed** 2016-04-25 09:50 UTC
Labels: bug, map
