### ISSUE TITLE
Specific tiles are empty

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#111] opened 2015-12-20 23:51 UTC
If you go to the center of Tsibili, it's empty on some rasters and corrupted on others. Happens on Docker and website. It's ok on vector map.

tile ids:
14/10230/6100
14/10231/6100
14/10231/6101
14/10230/6101

For example:
http://klokantech-2.tileserver.com/osm-bright/14/10230/6100.png?key=WQ5sRntXphOrWgesmtmU

Images:
<img width="969" alt="screen shot 2015-12-21 at 00 49 25" src="https://cloud.githubusercontent.com/assets/494223/11920961/b5397d4c-a77c-11e5-999b-04d38c3ad7c1.png">
<img width="970" alt="screen shot 2015-12-21 at 00 49 57" src="https://cloud.githubusercontent.com/assets/494223/11920965/c905171e-a77c-11e5-93dd-16ecece71b58.png">
<img width="964" alt="screen shot 2015-12-21 at 00 50 26" src="https://cloud.githubusercontent.com/assets/494223/11920969/da101e3c-a77c-11e5-8d9c-ebcc319751cb.png">

**Comment by klokan** [comment] 2015-12-22 21:31
The relevant vector tiles appears in the JavaScript tile inspector:
http://klokantech.github.io/ol3-sandbox/vector/tile-inspector.html#http://osm2vectortiles.tileserver.com/v1.json|41.70886829782091|44.78902816772461|14

We should probably try to get the logs from mapnik about the rendering. Looks strange - as a corrupted tiles ignored by mapnik for some reason.

**Comment by hyperknot** [comment] 2015-12-23 06:12
I think mapnik outputs logs, for example the missing markers are always visible in docker.

**Comment by klokan** [comment] 2016-02-22 15:42
The vector tile is really not in there (in tile inspector appears only upper zoom levels).

Probably duplicate problem to #116

**Comment by lukasmartinelli** [comment] 2016-04-11 09:07
This will consolidate the reports from https://github.com/osm2vectortiles/osm2vectortiles/issues/112 and https://github.com/osm2vectortiles/osm2vectortiles/issues/194.

**Comment by manuelroth** [comment] 2016-07-14 11:06
As this empty tiles do not appear anymore, I will close this issue.

**Closed by manuelroth** 2016-07-14 11:06 UTC
Labels: bug, low-priority

**Comment by stephankn** [comment] 2016-07-19 13:52
was there any fix applied  or is there additional checks in the build scripts? I am under the impression it was mentioned to add additional checks. I didn't see any referenced commit. Or is it pure luck that the issue is no longer observed? In this case closing the issue is probably a bad idea.

**Comment by lukasmartinelli** [comment] 2016-07-26 18:12
Yes this was before the rerendering of #326. But process has not changed since sadly.
It re-emerged as #380.
