### ISSUE TITLE
Natural Earth data for upper zoom levels

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#46] opened 2015-10-23 17:42 UTC
We should verify how to make good looking upper zoom levels in open-streets.tm2source.

It seems a general practice is to utilise instead of OSM database the data from Natural Earth Data (http://www.naturalearthdata.com).

MapBox Streets may work a lot with "scalerank" which originates in NaturalEarth Data and is not available in OSM (to my knowledge - check it). Without this the maps may be overfilled with content and may look uglier.

https://www.mapbox.com/guides/osm-and-mapbox/#mapbox-streets-and-openstreetmap:
> Data for Mapbox Streets comes primarily from OpenStreetMap, with Natural Earth and our own tweaks used for some parts.

https://www.mapbox.com/blog/2012-08-09-mapbox-streets-design-update/:
> Previously our zoomed out views of the globe used city labels from Natural Earth, and we only started showing OpenStreetMap names after you zoomed in a bit. This worked well because Natural Earth has a much more granular ranking classification system aimed at helping cartographers choose the right sizes and density of labels for their maps. The Natural Earth place names, for the most part, are only in English. But we still want to take advantage of the many locales that OpenStreetMap contributors have put together, especially to show place names in their local language and writing system.
>
> To get the best of both worlds we joined Natural Earth’s scalerank information into our OpenStreetMap places table. This was not straight-forward ...

The open source of information regarding usage of Natural Earth data in vector tiles:

https://github.com/mapzen/vector-datasource

https://github.com/mapbox/natural-earth-tm2

It seems that https://maps.wikimedia.org/ #28 are not using the Natural Earth data at all ... right? Do we have any comments from them on this point?

**Comment by klokan** [comment] 2015-10-23 20:36
The relevant code to run on imposm imported data for enrichment with scalerank:
https://github.com/mapbox/osm-place-ranks

**Comment by klokan** [comment] 2015-10-27 20:31
Country labels with scalerank and labelrank for upper zoom levels could be possibly taken from:
https://github.com/osm2vectortiles/natural-earth-tm2/blob/master/natural-earth.tm2source/data.yml#L355

**Comment by klokan** [comment] 2015-10-28 14:56
We probably don't need to merge natural-earth into osm database for our vector tiles. We can have two separated databases in Postgres - and the .tm2source style could query both.

This approach is used in Mapzen Vector Tiles (see https://github.com/mapzen/vector-datasource/blob/master/queries/landuse.jinja2) and was used in early MapBox Streets.

@lukasmartinelli could you please reply on:
> It seems that https://maps.wikimedia.org/ #28 are not using the Natural Earth data at all ... right? Do we have any comments from them on this point?

**Comment by lukasmartinelli** [comment] 2015-10-28 15:22
> It seems that https://maps.wikimedia.org/ #28 are not using the Natural Earth data at all ... right? Do we have any comments from them on this point?

I will ask them specifically but from the two people we asked last time this topic never popped up.

**Comment by lukasmartinelli** [comment] 2015-10-28 15:28
Quality of the labels is indeed quite noticable.

**Mapbox OSM Bright**

![mapbox_studio_classic](https://cloud.githubusercontent.com/assets/1288339/10793282/781f9d30-7d90-11e5-90c8-f96d37d295c6.png)

**Wikimedia**

![wikimedia_maps_beta](https://cloud.githubusercontent.com/assets/1288339/10793329/bcd50820-7d90-11e5-8d96-7d9d515742bc.png)

**Comment by klokan** [comment] 2015-10-28 15:31
@lukasmartinelli application of https://github.com/mapbox/osm-place-ranks for places looks pretty straightforward.
Where would it fit into our import process?
Shall this run always in the `import` container?

**Comment by lukasmartinelli** [comment] 2015-10-28 15:52
> Where would it fit into our import process?
> Shall this run always in the import container?

I would like to create a new container `rank-places` like `import-water` because then each container has one single purpose and process. And from what I see it does not matter whether this runs before `import` or after `import`.

We need to query the improved places table `ne_cities` in the source project so the component is required to run otherwise the `tm2source` will fail.

I will write that container, shouldn't take long. @manuelroth can then query the data at a later stage of our zoom level improvements.

**Comment by klokan** [comment] 2015-10-28 16:06
- [ ] rank-places modification
Are you sure this should be a separate step?

They write:
> These can be from a full planet dump, a regional extract...

It must run after (or together with) an planet import - because it is modifying the imposm's `osm_places` table. The `ne_cities` table is only a temporary table  - and probably does not need to be used in our tm2source directly. Maybe it is not even required once you run the rank-places.py, and could be then removed from PostGIS...

- [ ] natural_earth
But we will need a separate docker `import_natural_earth` which will import our Postgis the "natural_earth" database - see `./util/setup_db.sh` from https://github.com/mapbox/natural-earth-tm2. This should be quite straight forward and it does for sure belongs to a separate docker.

Could you please look into these two things?

**Comment by lukasmartinelli** [comment] 2015-10-28 16:29
Oh did not look to deeply into `rank-places.py` before, but it is a `UPDATE` so it must run after import.
And because it requires the `python` runtime it is also better to use a separat image.

What it does:

1. Merge overrides into natural earth data
2. Query natural earth data 
3. Query OSM data
4. Do fuzzy matching in python of both results
5. Update `osm_places`

I will first try to fix the water problem. Then I will look into the ranks.

**Comment by klokan** [comment] 2015-10-28 17:05
OK. Thanks.

BTW I think it is not dependent on the natural earth data at all - is uses only a single .sql file included in the repo: [ne_cities.sql](https://github.com/mapbox/osm-place-ranks/blob/master/ne_cities.sql) - so points 1. and 2. are not true IMHO.
Anyway - we will need both points mentioned above for the scalerank to appear in the vector tiles... THX!

**Comment by lukasmartinelli** [comment] 2015-11-09 19:30
Didn't get https://github.com/mapbox/osm-place-ranks to work after first try. Doesn't find any matches in my case - it is pretty hacky code, I wonder how it worked once.

Perhaps we just show the cities directly from natural earth data (and leave the translations from OSM be for lower zoom levels). Need to check that out.

**Comment by klokan** [comment] 2015-11-09 20:14
Perhaps we could use the OSM-ID to NaturalEarthData linking which KlokanTech has made about two years ago for GeoSEO applications: http://www.mapranksearch.com/geoseo/ - it would be 12092 records (for ne_10m_geography_regions, ne_10m_admin_0_countries, ne_10m_admin_0_map_subunits, ne_10m_admin_1_states_provinces, ne_10m_populated_places) with a structure like:
[ne_title VARCHAR, type_id VARCHAR, osm_id VARCHAR]
For example:
`Zürich|10m_cultural/ne_10m_populated_places.shp:7161|relation/1682248`
for http://www.openstreetmap.org/relation/1682248
Could you please check if it be helpful enough for binding the ranks to OSM-IDs?

**Comment by lukasmartinelli** [comment] 2015-11-10 08:14
We could use it to just do the mapping - that probably would be the best solution but also requires most time. 

Let's try simple name matching first and see how far we get - perhaps it is good enough.
In https://github.com/osm2vectortiles/osm2vectortiles/commit/cfa4ab5db33eac0a04819a8db90ed97d9bceb34d I just do very simple name matching in PostgreSQL (also tried using fuzzy matching in PostgreSQL like in the Python script but results where not that much better (just had more false positives) - so better have less scaleranks at all than wrong scaleranks in my opinon).

We now import the natural earth data in https://github.com/osm2vectortiles/osm2vectortiles/tree/feature/natural-earth so we can start querying it.

This introduced two additional docker containers (`rank-places` and `import-natural-earth`) but at one point we have to simplify the amount of docker containers again e.g. just use one import container for external data.

**Comment by lukasmartinelli** [comment] 2015-11-10 08:45
We can still use OSM data and just merge the scalerank for the following features:

- Cities
- Marine (Oceans and Seas)
- Countries

For admin we have to try out how it looks if we just use Naturalearth data instead of OSM data - I don't know how detailed it is.

**Comment by lukasmartinelli** [comment] 2015-11-10 13:45
We just found out that actually all admin layers in Mapbox have the OSM id set to `0` until zoom level 13.
On zoom level 14 they have an OSM id.

This looks like they use natural earth data for admin down to z13 and then use OSM data.

**Comment by lukasmartinelli** [comment] 2015-11-10 14:15
Wrong assumption -> Mapbox **only** uses OpenStreetMap data for boundaries.
We can actually see that they have the same fails in boundaries as we have with OSM data.
In v6 they mark it as maritime so that it looks better.

What we have to add is **marking all boundaries which are in a water polygon as `maritime=1`**

Below is all Mapbox with the same problems we have.

![osm_bright_2](https://cloud.githubusercontent.com/assets/1288339/11064452/8d32b086-87bd-11e5-948d-1f690ea98e71.png)

![osm_bright_2](https://cloud.githubusercontent.com/assets/1288339/11064406/5b0bc80e-87bd-11e5-8799-071cc75ea252.png)


![osm_bright_2](https://cloud.githubusercontent.com/assets/1288339/11064463/a42c8b7c-87bd-11e5-91f8-cdc026a94f5f.png)

**Comment by lukasmartinelli** [comment] 2015-11-10 16:04
What we are doing now with the borders:
- We take the maritime borders from OSM data because Natural Earth only provides partial data there
- And we take all other data we take from Natural Earth (including disputed, country borders)

**Comment by manuelroth** [comment] 2015-11-10 21:16
Marine Labels:
- Mapbox did certainly not just take the natural earth scaleranks for marine labels
- But I just figured out, that if we add one to the natural earth scalerank of the marine labels we get very close to it.
- There are still labels which have too high scalerank

**Comment by lukasmartinelli** [comment] 2015-11-10 21:20
> But I just figured out, that if we add one to the natural earth scalerank of the marine labels we get very close to it.

:+1: 

> There are still labels which have too high scalerank

Yes we have to write a normalize function that ensures the values are in the range specified by Mapbox.
I did something similar for the `place_label` query.

**Comment by manuelroth** [comment] 2015-11-11 11:25
I identified major problems on following layers:
- [ ] water polygons (lakes) look not good on level 0 to 5
- [ ] we show too many marine labels with wrong scalerank
- [ ] country labels need improvements on level 3
- [ ] in north america we show less place labels on level 4 to 5
- [ ] since we use osm data starting level 7 on the admin layer some borders are still broken

**Comment by manuelroth** [comment] 2015-11-11 11:27
> water polygons (lakes) look not good on level 0 to 5

Water polygons look now perfect, we use natural earth data from zoomlevel 0 - 5

**Comment by lukasmartinelli** [comment] 2015-11-11 12:24
> since we use osm data starting level 7 on the admin layer some borders are still broken

You mean OSM borders that are **in the water** but are not marked as maritime?
Can we even solve this without fiddling with the data?

At least it looks much better from far away - having the weird borders show up when you zoom in looks much better and is perhaps even expected (I mean there must be some reason they exist - otherwise people wouldn't tag them).



> we show too many marine labels with wrong scalerank

Is it a problem of the matching - that some entities have higher scalerank than they should have from natural earth?
Perhaps I match the wrong OSM ids with natural earth data?

**Comment by manuelroth** [comment] 2015-11-11 12:52
> You mean OSM borders that are in the water but are not marked as maritime?
Can we even solve this without fiddling with the data?

Yes, I can't see a straight forward way to solve this right now.

**Comment by manuelroth** [comment] 2015-11-11 12:59
I finished the work you started with the natural earth scalerank for country labels and removed the population based calculation. 
But I still don't know how they decide when to show the iso codes of the countries.
![bildschirmfoto 2015-11-11 um 13 54 02](https://cloud.githubusercontent.com/assets/1810384/11091569/0507a382-887c-11e5-8404-f21abc3a8b94.png)
Its not based on the length of the country name, it must have something to do with the density of labels.

**Comment by lukasmartinelli** [comment] 2015-11-11 13:47
Weird so the data of Mapbox has the `iso_code`  set as name? In v6 they provide it as additional field.

Is the scalerank attribute set for the screenshot on the left? Because then Brazil and Mexico should be bigger..?

**Comment by manuelroth** [comment] 2015-11-11 13:59
> Weird so the data of Mapbox has the iso_code set as name? In v6 they provide it as additional field.

Yes, they set the iso code as name also in the translation fields (name_en ect.). The scalerank is set, there are also differences Mapbox sets scalerank for brazil and mexico to 1 and natural earth to 2.

**Comment by lukasmartinelli** [comment] 2015-11-11 14:06
> But I still don't know how they decide when to show the iso codes of the countries.

Have you tried using the `iso_code` as name for countries with e.g. a `scalerank > 3`?

And I saw you use the `labelrank` from Natural Earth instead of `scalerank` - you know what the difference is there?

**Comment by manuelroth** [comment] 2015-11-11 14:10
Update on the marine labels:
- Most of the things we show as polygons (left side) Mapbox shows as linestring. What confuses me, is that these seas are not even present as linestring (nor in osm data or natural earth).
 - Example (Black Sea):
![bildschirmfoto 2015-11-11 um 15 01 09](https://cloud.githubusercontent.com/assets/1810384/11092711/a148c902-8885-11e5-8a46-319291dfc889.png)
- Most of the bays we show, are not present in mapbox streets v5
![bildschirmfoto 2015-11-11 um 15 09 47](https://cloud.githubusercontent.com/assets/1810384/11092805/4fc9f12c-8886-11e5-9e61-6d7c6e638632.png)

**Comment by manuelroth** [comment] 2015-11-11 14:21
> Have you tried using the iso_code as name for countries with e.g. a scalerank > 3?

I will try that, maybe we come close enough with this.

> And I saw you use the labelrank from Natural Earth instead of scalerank - you know what the difference is there?

I suppose the labelrank is for labels, I don't now what the difference is. I choose it because in many cases it is similar to the scalerank of mapbox has on the country label layer.

**Comment by manuelroth** [comment] 2015-11-11 14:33
I tryed your idea ( showing iso_codes as name for countries with scalerank > 3). The problem is that not many countries have set there iso code. Right now it looks like this:
![bildschirmfoto 2015-11-11 um 15 29 17](https://cloud.githubusercontent.com/assets/1810384/11093248/6ff1dafc-8889-11e5-915b-de10933949c0.png)
I will try to add the iso code of natural earth, and see if it looks better.

**Comment by klokan** [comment] 2015-11-11 14:38
Could you please try the latest OSM Bright 2 in MapBox Studio Classic - the one which is using Streets V6? I tend recently to be move V6 compatible then V5 on upper zoom levels - whenever possible.

**Comment by klokan** [comment] 2015-11-11 14:40
See #71

**Comment by klokan** [comment] 2015-11-11 14:52
If I remember well `labelrank` in Natural Earth is if you want to reduce number of labels displayed (typically show smaller number of labels on the map) while `scalerank` is about importance of the features  - if it is more important then others then you can use bigger font or display it on upper zoom levels then other features.

**Comment by manuelroth** [comment] 2015-11-11 16:08
With mapbox streets v6 (right side) they moved back to the full country name. I tryed to come close to what they have, but it still needs some refinement. 
![bildschirmfoto 2015-11-11 um 16 57 58](https://cloud.githubusercontent.com/assets/1810384/11095502/88326918-8895-11e5-8971-86016f41e2a2.png)

@lukasmartinelli I found some issues with the name comparison. 
- For example US:  
 - osm name: United States of America  and  natural earth name: United States
- or Czech:
 - osm name: Czech Republic and natural earth name: Czech Rep.
I updated the sql function with the necessary changes.

**Comment by lukasmartinelli** [comment] 2015-11-11 16:26
Hey @manuelroth that looks much better!! Thanks!

> @lukasmartinelli I found some issues with the name comparison.

Great. When importing with the container you should see how many rows have been updated.
We could go back to fuzzy matching - but I am a bit afraid we match too many.

We also seem to have quite different marine labels and they are quite difficult to get right from OSM data with matching alone. What about using only Natural Earth data for marine labels instead of merging it?
We could use the marine polygons (or there is also a point table) from Natural Earth for labeling and don't support all translations on seas.

**Closed** 2015-11-17 15:42 UTC
Labels: URGENT
